# Generated by Django 4.2.2 on 2023-06-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='colors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
